{% set name = "montreal-forced-aligner" %}
{% set version = "3.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name | replace("-", "_") }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2736e067838948a4c50a21def8e65670dd5f9f42ca9205cdffa73ac1256bcc14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:mfa_cli
  run_exports:
    - {{ pin_subpackage('montreal-forced-aligner', max_pin='x.x.x') }}

requirements:
  host:
    - setuptools
    - setuptools_scm
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - kaldi
    - pynini
    - openfst
    - baumwelch
    - ngram
    - sox
    - ffmpeg
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - pyyaml
    - biopython
    - praatio =6.0.0
    - sqlalchemy >=2.0
    - dataclassy
    - numba
    - kneed
    - pgvector
    - pgvector-python
    - postgresql
    - sqlite
    - hdbscan
    - psycopg2
    - scikit-learn
    - rich
    - rich-click
    - kalpy

test:
  requires:
    - python {{ python_min }}
    - pytest
    - mock
    - pytest-mypy
    - pytest-cov
    - pytest-timeout
  source_files:
    - tests
  commands:
    - mfa --help
    - mfa_update
    - mfa server init -p test
    - pytest tests/test_acoustic_modeling.py
    - mfa server stop -p test
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.diarization
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.online
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner.vad
    - montreal_forced_aligner.validation
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Forced aligner for speech to text alignment
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
