{% set name = "montreal-forced-aligner" %}
{% set version = "2.0.0b8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Montreal Forced Aligner-{{ version }}.tar.gz
  sha256: 4f890ca0dd8a5f453c89a4ec8a6ad4285df36250ccbb574d9f6187d4ebb55071

build:
  number: 0
  skip: True  # [py<39]
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:main

requirements:
  build:
  host:
    - setuptools
    - setuptools_scm
    - wheel
    - python
    - pip
  run:
    - python
    - kaldi
    - sox
    - openfst  # [not win]
    - baumwelch  # [not win]
    - ngram  # [not win]
    - pynini  # [not win]
    - librosa
    - numpy
    - tqdm
    - requests
    - colorama
    - pyyaml
    - praatio

test:
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.segmenter
    - montreal_forced_aligner.speaker_classifier
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils
    - montreal_forced_aligner.validator

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Forced aligner for speech to text alignment'
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
