{% set name = "montreal-forced-aligner" %}
{% set version = "2.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Montreal Forced Aligner-{{ version }}.tar.gz
  sha256: e3a09186d1836df96ab4f28db212cd95684509b2c86328bdb8aa3f9d9ebd972b

build:
  number: 3
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - setuptools
    - setuptools_scm
    - wheel
    - python
    - pip
    - kaldi
    - sox
    - ffmpeg
    - openfst
    - baumwelch
    - ngram
    - pynini
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - colorama
    - ansiwrap
    - pyyaml
    - biopython  =1.79
    - praatio =5.1.1
    - sqlalchemy =1.4.46
    - dataclassy
  run:
    - python
    - kaldi
    - pynini
    - openfst
    - baumwelch
    - ngram
    - sox
    - ffmpeg
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - colorama
    - ansiwrap
    - pyyaml
    - biopython  =1.79
    - praatio =5.1.1
    - sqlalchemy =1.4.46
    - dataclassy

test:
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.segmenter
    - montreal_forced_aligner.speaker_classifier
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils
    - montreal_forced_aligner.validation

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Forced aligner for speech to text alignment
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
