{% set name = "montreal-forced-aligner" %}
{% set version = "2.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Montreal Forced Aligner-{{ version }}.tar.gz
  sha256: a414059376eb9cd0410bc260ab55dc7a45324f918472c738f942f64fad208add

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mfa = montreal_forced_aligner.command_line.mfa:mfa_cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - setuptools
    - setuptools_scm
    - wheel
    - python
    - pip
    - kaldi
    - sox
    - ffmpeg
    - openfst
    - baumwelch
    - ngram
    - pynini
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - pyyaml
    - biopython =1.79
    - praatio =6.0.0
    - sqlalchemy >=2.0
    - dataclassy
    - numba
    - kneed
    - matplotlib-base
    - seaborn
    - pgvector
    - pgvector-python
    - postgresql
    - hdbscan
    - psycopg2
    - click
    - rich
    - rich-click
  run:
    - python
    - kaldi
    - pynini
    - openfst
    - baumwelch
    - ngram
    - sox
    - ffmpeg
    - librosa
    - pysoundfile
    - numpy
    - tqdm
    - requests
    - pyyaml
    - biopython =1.79
    - praatio =6.0.0
    - sqlalchemy >=2.0
    - dataclassy
    - numba
    - kneed
    - matplotlib-base
    - seaborn
    - pgvector
    - pgvector-python
    - postgresql
    - hdbscan
    - psycopg2
    - click
    - rich
    - rich-click

test:
  commands:
    - mfa --help
  imports:
    - montreal_forced_aligner
    - montreal_forced_aligner.acoustic_modeling
    - montreal_forced_aligner.alignment
    - montreal_forced_aligner.command_line
    - montreal_forced_aligner.corpus
    - montreal_forced_aligner.diarization
    - montreal_forced_aligner.dictionary
    - montreal_forced_aligner.g2p
    - montreal_forced_aligner.ivector
    - montreal_forced_aligner.language_modeling
    - montreal_forced_aligner.online
    - montreal_forced_aligner.transcription
    - montreal_forced_aligner.vad
    - montreal_forced_aligner.validation
    - montreal_forced_aligner._version
    - montreal_forced_aligner.abc
    - montreal_forced_aligner.config
    - montreal_forced_aligner.data
    - montreal_forced_aligner.exceptions
    - montreal_forced_aligner.helper
    - montreal_forced_aligner.models
    - montreal_forced_aligner.textgrid
    - montreal_forced_aligner.utils

about:
  home: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Forced aligner for speech to text alignment
  description: |
    The Montreal Forced Aligner is a command line utility for performing forced alignment of speech datasets using
    Kaldi <http://kaldi-asr.org/>.
  doc_url: https://montreal-forced-aligner.readthedocs.io/
  dev_url: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner

extra:
  recipe-maintainers:
    - mmcauliffe
